#!/bin/csh
#
#    test case 'eda-n-n-ump2
#    Hui's energy decomposition analysis
#    system is N2 (internal bond decomposition)
#    UMP2 level test of each N atom.
#
set ierr=0
set ethrsh=0.01
#
#      checking only "own basis" results, which is the first set.
set  ES0=-329.08
set  EX0=-473.95
set REP0=1280.84
set POL0=-585.47
set DIS0=-103.86
set TIH0=-107.66
set TIM0=-211.52

set  ES=`grep "ELECTROSTATIC ENERGY                  ES=" $1 | head -1 | awk '{ print $5 }'`0
set  EX=`grep "EXCHANGE ENERGY                       EX=" $1 | head -1 | awk '{ print $5 }'`0
set REP=`grep "REPULSION ENERGY                     REP=" $1 | head -1 | awk '{ print $5 }'`0
set POL=`grep "POLARIZATION ENERGY                  POL=" $1 | head -1 | awk '{ print $5 }'`0
set DIS=`grep "MP2 DISPERSION ENERGY               DISP=" $1 | head -1 | awk '{ print $6 }'`0
set TIH=`grep "TOTAL INTERACTION ENERGY HF OR DFT     E=" $1 | head -1 | awk '{ print $9 }'`0
set TIM=`grep "TOTAL INTERACTION ENERGY MP2           E=" $1 | head -1 | awk '{ print $7 }'`0
#
set ESerr=`$chkabs $ES $ES0 $ethrsh`
if($status != 0) set ierr=1 
set EXerr=`$chkabs $EX $EX0 $ethrsh`
if($status != 0) set ierr=1 
set REPerr=`$chkabs $REP $REP0 $ethrsh`
if($status != 0) set ierr=1 
set POLerr=`$chkabs $POL $POL0 $ethrsh`
if($status != 0) set ierr=1 
set DISerr=`$chkabs $DIS $DIS0 $ethrsh`
if($status != 0) set ierr=1 
set TIHerr=`$chkabs $TIH $TIH0 $ethrsh`
if($status != 0) set ierr=1 
set TIMerr=`$chkabs $TIM $TIM0 $ethrsh`
if($status != 0) set ierr=1 
#
echo -n "ESerr=$ESerr EXerr=$EXerr REPerr=$REPerr DISerr=$DISerr POLerr=$POLerr TIHerr=$TIHerr TIMerr=$TIMerr"
exit $ierr 
