#!/bin/csh
#
#    test case 'eda-cu-wat'
#    Hui's energy decomposition analysis
#    system is copper +2 ion, plus one water.
#    RHF level test
#
set ierr=0
set ethrsh=0.01
#
#      checking only "own basis" results, which is the first set.
set  ES0=-98.85
set  EX0=-22.33
set REP0=61.58
set POL0=-59.77
set TIH0=-119.37

set  ES=`grep "ELECTROSTATIC ENERGY                  ES=" $1 | head -1 | awk '{ print $5 }'`0
set  EX=`grep "EXCHANGE ENERGY                       EX=" $1 | head -1 | awk '{ print $5 }'`0
set REP=`grep "REPULSION ENERGY                     REP=" $1 | head -1 | awk '{ print $5 }'`0
set POL=`grep "POLARIZATION ENERGY                  POL=" $1 | head -1 | awk '{ print $5 }'`0
set TIH=`grep "TOTAL INTERACTION ENERGY HF OR DFT     E=" $1 | head -1 | awk '{ print $9 }'`0
#
set ESerr=`$chkabs $ES $ES0 $ethrsh`
if($status != 0) set ierr=1 
set EXerr=`$chkabs $EX $EX0 $ethrsh`
if($status != 0) set ierr=1 
set REPerr=`$chkabs $REP $REP0 $ethrsh`
if($status != 0) set ierr=1 
set POLerr=`$chkabs $POL $POL0 $ethrsh`
if($status != 0) set ierr=1 
set TIHerr=`$chkabs $TIH $TIH0 $ethrsh`
if($status != 0) set ierr=1 
#
echo -n "ESerr=$ESerr EXerr=$EXerr REPerr=$REPerr POLerr=$POLerr TIHerr=$TIHerr"
exit $ierr 
