#!/bin/csh
#
#    test case 'eda-wat2-ublyp'
#    Hui's energy decomposition analysis
#    system is two waters 
#    this is a closed shell DFT test, pretending UHF on the two waters.
#    consequently the UHF answers must match the RHF ones exactly,
#    so just for funsies, we check the "ALL basis" results instead.
#
set ierr=0
set ethrsh=0.01
#
#      checking only "all basis" results, which is the second set.
set  ES0=-9.53
set  EX0=-2.66
set REP0=14.38
set POL0=-3.32
set DSD0=-2.89
set TID0=-4.02

set  ES=`grep "ELECTROSTATIC ENERGY                  ES=" $1 | sed -n -e "2 p" | awk '{ print $5 }'`0
set  EX=`grep "EXCHANGE ENERGY                       EX=" $1 | sed -n -e "2 p" | awk '{ print $5 }'`0
set REP=`grep "REPULSION ENERGY                     REP=" $1 | sed -n -e "2 p" | awk '{ print $5 }'`0
set POL=`grep "POLARIZATION ENERGY                  POL=" $1 | sed -n -e "2 p" | awk '{ print $5 }'`0
set DSD=`grep "DFT DISPERSION ENERGY               DISP=" $1 | sed -n -e "2 p" | awk '{ print $6 }'`0
set TID=`grep "TOTAL INTERACTION ENERGY HF OR DFT     E=" $1 | sed -n -e "2 p" | awk '{ print $9 }'`0
#
set ESerr=`$chkabs $ES $ES0 $ethrsh`
if($status != 0) set ierr=1 
set EXerr=`$chkabs $EX $EX0 $ethrsh`
if($status != 0) set ierr=1 
set REPerr=`$chkabs $REP $REP0 $ethrsh`
if($status != 0) set ierr=1 
set POLerr=`$chkabs $POL $POL0 $ethrsh`
if($status != 0) set ierr=1 
set DSDerr=`$chkabs $DSD $DSD0 $ethrsh`
if($status != 0) set ierr=1 
set TIDerr=`$chkabs $TID $TID0 $ethrsh`
if($status != 0) set ierr=1 
#
echo -n "ESerr=$ESerr EXerr=$EXerr REPerr=$REPerr POLerr=$POLerr DSDerr=$DSDerr TIDerr=$TIDerr"
exit $ierr 
