#!/bin/bash

rhf0=-1363.0558913779
dsum10=4.7416520799
dsum20=7.0453262263

rhf=`grep "FINAL RHF ENERGY " $1 | tail -n 1 | awk '{print $5}'`
dsum1=`grep "^ \+DIAGONAL SUM D=" $1 | head -n 1 | awk '{print $4}'`
dsum2=`grep "^ \+DIAGONAL SUM D=" $1 | tail -n 1 | awk '{print $4}'`

tolE0=$tolE

error=0

#rhf energy
diffrhf=`$chkabs $rhf $rhf0 $tolE0`
if [ $? -ne 0 ]
then
  error=$(( $error + 1 ))
fi
#vvos diagonal sum (before localization)
diffdsum1=`$chkabs $dsum1 $dsum10 $tolE0`
if [ $? -ne 0 ]
then
  error=$(( $error + 1 ))
fi
#vvos diagonal sum (after localization)
diffdsum2=`$chkabs $dsum2 $dsum20 $tolE0`
if [ $? -ne 0 ]
then
  error=$(( $error + 1 ))
fi

printf "RHF=%12.8f; DSUM=%12.8f; DSUM(loc)=%12.8f\n" $diffrhf $diffdsum1 $diffdsum2
exit $error
