#!/bin/csh
#set MOE0=-229.3943496933
set VBE0=-230.76870107

#set MOE=`grep "MP2 Energy from Gamess run" $1 | tail -1 | awk '{ print $7 }'`0
set VBE=`grep "FINAL VB2000 ENERGY" $1 | tail -1 | awk '{ print $6 }'`0

set ierr=0
#set MOEerr=`$chkabs $MOE $MOE0 $tolE`
#if($status != 0) set ierr=1 
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
echo -n "VBEerr=$VBEerr. "
#echo -n "MOEerr=$MOEerr VBEerr=$VBEerr. "

exit $ierr 
