#!/bin/csh
set MOE0=-76.0240386072
set VBE0=-76.0668884231
set VBD0=1.866386

set MOE=`grep "FINAL RHF" $1 | awk '{ print $5 }'`0
set VBE=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0
set nVBD=0`grep -n DEBYE $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set VBD=`sed -n -e "$nVBD p" $1 | awk '{ print $4 }'`

set ierr=0
set MOEerr=`$chkabs $MOE $MOE0 $tolE`
if($status != 0) set ierr=1 
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
set VBDerr=`$chkabs $VBD $VBD0 $tolD`
if($status != 0) set ierr=1
echo -n "MOEerr=$MOEerr VBEerr=$VBEerr VBDerr=$VBDerr."
exit $ierr 
