#!/bin/csh
set MOE0=-40.2416023819
set VBE0=-40.2435441021

set MOE=`grep "FINAL GVB" $1 | awk '{ print $5 }'`0
set VBE=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0

set ierr=0
set MOEerr=`$chkabs $MOE $MOE0 $tolE`
if($status != 0) set ierr=1 
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
echo -n "MOEerr=$MOEerr VBEerr=$VBEerr. "
exit $ierr 
