#!/bin/csh
set MOE0=-91.6444000435
set VBE0=-91.65881727

set MOE=`grep "FINAL RHF" $1 | tail -1 | awk '{ print $5 }'`0
set VBE=`grep "FINAL VB2000 ENERGY" $1 | tail -1 | awk '{ print $6 }'`0

set ierr=0
set MOEerr=`$chkabs $MOE $MOE0 $tolE`
if($status != 0) set ierr=1 
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
echo -n "MOEerr=$MOEerr VBEerr=$VBEerr. "
exit $ierr 
