#!/bin/csh
#
#   this test usually varies about 5 in the 8th digit due to the RI,
#   the specific answer below is from ifort/mkl/linux64
#
set E0=-2259.0955125948
set tolEnew=0.00000010

set E=`grep "FINAL ROHF" $1 | awk '{ print $5 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolEnew`
if($status != 0) set ierr=1 
echo -n "Eerr=$Eerr. "
exit $ierr 
