#!/bin/csh
set R_REF=-0.6817046732
set E_REF=-1673730.574
set T_REF=261.88135682

set R=`grep "US asymmetric stretch" $1 | tail -n 1 | awk '{ print $5 }'`0
set E=`grep "POT  ENERGY" $1 | tail -n 1 | awk '{ printf "%20.3f",$4 }'`0
set T=`grep "TEMPERATURE" $1 | tail -n 1 | awk '{ print $3 }'`0
set ierr=0
set Rerr=`$chkabs $R $R_REF $tolR`
if($status != 0) set ierr=1 
set Eerr=`$chkabs $E $E_REF $tolEk`
if($status != 0) set ierr=1 
set Terr=`$chkabs $T $T_REF $tolTe`
if($status != 0) set ierr=1 
echo -n "Eerr=$Eerr Rerr=$Rerr Terr=$Terr. "
exit $ierr 

