#!/bin/bash
#SBATCH -J gamess-omp-offload-tests
#SBATCH -o %x-%j.out
#SBATCH --time 04:00:00
#SBATCH --constraint gpu
#SBATCH --nodes=1
#SBATCH --qos=regular
#SBATCH --account=XXXX_g

cd $SLURM_SUBMIT_DIR

## Load your module environment
##

OMP_NUM_THREADS=16 ./tests/runtest.py --folder=efmo-gpu-offload -n 4 --pre="./bin/my_ipcrm" --post="./bin/my_ipcrm"

OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2-gpu-offload/parallel/benz.inp 00 4 4 &> tests/rimp2-gpu-offload/parallel/benz.log
OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2-gpu-offload/parallel/c60.inp 00 4 4 &> tests/rimp2-gpu-offload/parallel/c60.log
OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2-gpu-offload/parallel/cor.inp 00 4 4 &> tests/rimp2-gpu-offload/parallel/cor.log

OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2grd-mpiomp/Br2.inp 00 4 4 &> tests/rimp2grd-mpiomp/Br2.log
OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2grd-mpiomp/I2.inp 00 4 4 &> tests/rimp2grd-mpiomp/I2.log
OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2grd-mpiomp/I2NCH.inp 00 4 4 &> tests/rimp2grd-mpiomp/I2NCH.log
OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2grd-mpiomp/benz.inp 00 4 4 &> tests/rimp2grd-mpiomp/benz.log
OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2grd-mpiomp/benz_optimize.inp 00 4 4 &> tests/rimp2grd-mpiomp/benz_optimize.log
OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2grd-mpiomp/cor.inp 00 4 4 &> tests/rimp2grd-mpiomp/cor.log
OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2grd-mpiomp/w2o2.hess.ecp.inp 00 4 4 &> tests/rimp2grd-mpiomp/w2o2.hess.log
OMP_NUM_THREADS=16 ./rungms-dev tests/rimp2grd-mpiomp/c60.inp 00 4 4 &> tests/rimp2grd-mpiomp/c60.log

cd tests
./checkgms.py
./checkgms.py -v -p
