#!/bin/bash
#SBATCH -J gamess-omp-tests
#SBATCH -o %x-%j.out
#SBATCH --time 04:00:00
#SBATCH --constraint cpu
#SBATCH --nodes=1
#SBATCH --qos=regular
#SBATCH --account=XXXX

cd $SLURM_SUBMIT_DIR

## Load your module environment
##

OMP_NUM_THREADS=4  ./rungms-dev tests/rimp2grd-mpiomp/Br2.inp 00 4 4 &> tests/rimp2grd-mpiomp/Br2.log
OMP_NUM_THREADS=4  ./rungms-dev tests/rimp2grd-mpiomp/I2.inp 00 4 4 &> tests/rimp2grd-mpiomp/I2.log
OMP_NUM_THREADS=4  ./rungms-dev tests/rimp2grd-mpiomp/I2NCH.inp 00 4 4 &> tests/rimp2grd-mpiomp/I2NCH.log
OMP_NUM_THREADS=32  ./rungms-dev tests/rimp2grd-mpiomp/benz.inp 00 4 4 &> tests/rimp2grd-mpiomp/benz.log
OMP_NUM_THREADS=32  ./rungms-dev tests/rimp2grd-mpiomp/benz_optimize.inp 00 4 4 &> tests/rimp2grd-mpiomp/benz_optimize.log
OMP_NUM_THREADS=32  ./rungms-dev tests/rimp2grd-mpiomp/cor.inp 00 4 4 &> tests/rimp2grd-mpiomp/cor.log
OMP_NUM_THREADS=32  ./rungms-dev tests/rimp2grd-mpiomp/w2o2.hess.ecp.inp 00 4 4 &> tests/rimp2grd-mpiomp/w2o2.hess.ecp.log
OMP_NUM_THREADS=32  ./rungms-dev tests/rimp2grd-mpiomp/c60.inp 00 4 4  &> tests/rimp2grd-mpiomp/c60.log

cd tests
./checkgms.py
./checkgms.py -v -p
