C*MODULE RIMP2_1   *DECK RIMP2E2ACCPSMP
      SUBROUTINE RIMP2E2ACCPSMP(EIG,BB,BK1,BK2,Q,INFOCCBAT,E2,E2T,E2S,
     *     NAUXBAS,NORB,NOCC,NVIR,NOCCBAT,LENOCCBAT,IFILT3,IW,
     *     DDI_NN,DDI_MY,SMP_NP,SMP_ME)
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      LOGICAL GOPARR,DSKWRK,MASWRK
C
      DOUBLE PRECISION EIG(*),BB(NAUXBAS,NVIR,*),BK1(NAUXBAS,NVIR,*),
     *     BK2(NAUXBAS,NVIR,*),Q(*)
      INTEGER INFOCCBAT(2,NOCCBAT)
C
      INTEGER DDI_NN,DDI_MY,SMP_NP,SMP_ME
C
      COMMON /PAR   / ME,MASTER,NPROC,IBTYP,IPTIM,GOPARR,DSKWRK,MASWRK
C
      PARAMETER (ZERO=0.0D+00)
C
C     GENERATE 4C-2E ERI FROM 3 INDICES INTERMEDIATE MATRICES
C     AND ACCUMULATE MP2 CORRELATION ENERGY.
C     THIS SUBROUTINE IS FOR PARALLEL CALCULATIONS.
C
      TIMER = ZERO
      TIMEC = ZERO
      TIME4 = ZERO
      TIME5 = ZERO
C
      LENT3 = NAUXBAS*NVIR
      LENB = NAUXBAS*NVIR*LENOCCBAT
C
      MYNODE = DDI_MY+1
      NBATP1 = NOCCBAT/DDI_NN
      NBATP1C = NBATP1/2
C
      E2T = ZERO
      E2S = ZERO
      DO JBATP1 = 1, NBATP1
         J1BAT = (MYNODE-1)*NBATP1+JBATP1
         J1OCCBG = INFOCCBAT(1,J1BAT)+1
         J1OCCED = INFOCCBAT(1,J1BAT)+INFOCCBAT(2,J1BAT)
         CALL TSECND(TIMER0)
         IF(SMP_ME .EQ. 0) THEN
            DO JOCC = J1OCCBG, J1OCCED
               J = JOCC-J1OCCBG+1
               CALL RIMP2T3RD(BK1(1,1,J),LENT3,IFILT3,JOCC)
            END DO
         END IF
         CALL DDI_SMP_SYNC()
         CALL TSECND(TIMER1)
         TIMER = TIMER+(TIMER1-TIMER0)
         DO JPDIF = 1, DDI_NN/2
            J1NODE = MYNODE-JPDIF
            J2NODE = MYNODE+JPDIF
            IF(J1NODE .LE. 0)      J1NODE = J1NODE+DDI_NN
            IF(J2NODE .GT. DDI_NN) J2NODE = J2NODE-DDI_NN
C       WRITE(6,*) 'MYNODE=',MYNODE,'J1NODE=',J1NODE,'J2NODE=',J2NODE
            CALL TSECND(TIMEC0)
            IF(SMP_ME .EQ. 0) THEN
               J1RANK = (J1NODE-1)*SMP_NP
               J2RANK = (J2NODE-1)*SMP_NP
C               WRITE(6,*) 'MYNODE=',MYNODE,'J1RANK=',J1RANK,
C     *              'J2RANK=',J2RANK
               CALL DDI_ISEND(BK1,8*LENB,J1RANK,IREQ1)
               CALL DDI_IRECV(BK2,8*LENB,J2RANK,IREQ2)
               CALL DDI_WAIT(IREQ1)
               CALL DDI_WAIT(IREQ2)
            END IF
            CALL DDI_SMP_SYNC()
            CALL TSECND(TIMEC1)
            TIMEC = TIMEC+(TIMEC1-TIMEC0)
            J2BAT = (J2NODE-1)*NBATP1+JBATP1
            JOCCBG = INFOCCBAT(1,J2BAT)+1
            JOCCED = INFOCCBAT(1,J2BAT)+INFOCCBAT(2,J2BAT)
C            WRITE(6,*) 'J2BAT=',J2BAT,'JOCCBG=',JOCCBG,'JOCCED=',JOCCED
            IBATBG = (MYNODE-1)*NBATP1+1
            IBATED = MYNODE*NBATP1
            IF(MOD(DDI_NN,2) .EQ. 0 .AND. JPDIF .EQ. DDI_NN/2) THEN
               IF(MYNODE .LT. J2NODE) THEN
                  IF(JBATP1 .LE. NBATP1C) THEN
                     IBATBG = (MYNODE-1)*NBATP1+1
                     IBATED = (MYNODE-1)*NBATP1+NBATP1C
                  ELSE
                     IBATBG = (MYNODE-1)*NBATP1+NBATP1C+1
                     IBATED = MYNODE*NBATP1
                  END IF
               ELSE
                  IF(JBATP1 .LE. NBATP1C) THEN
                     IBATBG = (MYNODE-1)*NBATP1+NBATP1C+1
                     IBATED = MYNODE*NBATP1
                  ELSE
                     IBATBG = (MYNODE-1)*NBATP1+1
                     IBATED = (MYNODE-1)*NBATP1+NBATP1C
                  END IF
               END IF
            END IF
            CALL DDI_SMP_SYNC()
            DO IBAT = IBATBG, IBATED
               IOCCBG = INFOCCBAT(1,IBAT)+1
               IOCCED = INFOCCBAT(1,IBAT)+INFOCCBAT(2,IBAT)
C          WRITE(6,*) 'IBAT=',IBAT,'IOCCBG=',IOCCBG,'IOCCED=',IOCCED
               CALL TSECND(TIMER0)
               IF(SMP_ME .EQ. 0) THEN
                  DO IOCC = IOCCBG, IOCCED
                     I = IOCC-IOCCBG+1
                     CALL RIMP2T3RD(BB(1,1,I),LENT3,IFILT3,IOCC)
                  END DO
               END IF
               CALL DDI_SMP_SYNC()
               CALL TSECND(TIMER1)
               TIMER = TIMER+(TIMER1-TIMER0)
C
               CALL RIMP2TEIE2SMP(EIG,BB,BK2,Q,E2T,E2S,NAUXBAS,NORB,
     *              NOCC,NVIR,IOCCBG,IOCCED,JOCCBG,JOCCED,IBAT,J2BAT,
     *              TIME4,TIME5,SMP_NP,SMP_ME)
C
               CALL DDI_SMP_SYNC()
            END DO              !IBAT
         END DO                 !JPDIF
C
         IBATBG = (MYNODE-1)*NBATP1+1
         JOCCBG = J1OCCBG
         JOCCED = J1OCCED
         DO IBAT = IBATBG, J1BAT
            IOCCBG = INFOCCBAT(1,IBAT)+1
            IOCCED = INFOCCBAT(1,IBAT)+INFOCCBAT(2,IBAT)
C            WRITE(6,*) 'IBAT=',IBAT,'IOCCBG=',IOCCBG,'IOCCED=',IOCCED
            CALL TSECND(TIMER0)
            IF(SMP_ME .EQ. 0) THEN
               IF(IBAT .NE. J1BAT) THEN
                  DO IOCC = IOCCBG, IOCCED
                     I = IOCC-IOCCBG+1
                     CALL RIMP2T3RD(BB(1,1,I),LENT3,IFILT3,IOCC)
                  END DO
               ELSE
                  CALL DCOPY(LENT3*INFOCCBAT(2,IBAT),BK1,1,BB,1)
               END IF
            END IF
            CALL DDI_SMP_SYNC()
            CALL TSECND(TIMER1)
            TIMER = TIMER+(TIMER1-TIMER0)
C
            CALL RIMP2TEIE2SMP(EIG,BB,BK1,Q,E2T,E2S,NAUXBAS,NORB,NOCC,
     *           NVIR,IOCCBG,IOCCED,JOCCBG,JOCCED,IBAT,J1BAT,
     *           TIME4,TIME5,SMP_NP,SMP_ME)
C
            CALL DDI_SMP_SYNC()
         END DO                 !IBAT
      END DO                    !JBATP1
C
      CALL DDI_GSUMF(3100,E2T,1)
      CALL DDI_GSUMF(3101,E2S,1)
      E2 = E2T+E2S
C
      IF(MASWRK) WRITE(IW,9999) TIMER,TIMEC,TIME4,TIME5
      CALL FLSHBF(IW)
      RETURN
C
 9999 FORMAT(/1X,'TIME OF 3/3 INTEGRAL READ           =    ',F9.1,
     *       /1X,'TIME OF 3/3 INTEGRAL NETWORK COMM.  =    ',F9.1,
     *       /1X,'TIME OF TEI GENERATION              =    ',F9.1,
     *       /1X,'TIME OF MP2 ENERGY ACCUMULATION     =    ',F9.1)
      END
C*MODULE RIMP2_1   *DECK RIMP2E2ACCP2SMP
      SUBROUTINE RIMP2E2ACCP2SMP(EIG,BB,BK,Q,INFOCCBAT,E2,E2T,E2S,
     *     NAUXBAS,NORB,NOCC,NVIR,NOCCBAT,
     *     IW,DDI_NN,DDI_MY,SMP_NP,SMP_ME)
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      LOGICAL GOPARR,DSKWRK,MASWRK
C
      DOUBLE PRECISION EIG(*),BB(NAUXBAS,NVIR,*),BK(NAUXBAS,NVIR,*),Q(*)
      INTEGER INFOCCBAT(2,NOCCBAT)
C
      INTEGER DDI_NN,DDI_MY,SMP_NP,SMP_ME
C
      COMMON /PAR   / ME,MASTER,NPROC,IBTYP,IPTIM,GOPARR,DSKWRK,MASWRK
C
      INTEGER D_V,D_TA,D_TB
      COMMON /RIMPDD/ D_V,D_TA,D_TB
C
      PARAMETER (ZERO=0.0D+00)
C
C     GENERATE 4C-2E ERI FROM 3 INDICES INTERMEDIATE MATRICES
C     AND ACCUMULATE MP2 CORRELATION ENERGY.
C     THIS SUBROUTINE IS FOR PARALLEL CALCULATIONS.
C
      TIMEC = ZERO
      TIME4 = ZERO
      TIME5 = ZERO
C
      LENT3 = NAUXBAS*NVIR
C
      MYNODE = DDI_MY+1
      NBATP1 = NOCCBAT/DDI_NN
      NBATP1C = NBATP1/2
C
      E2T = ZERO
      E2S = ZERO
      DO JBATP1 = 1, NBATP1
         DO JPDIF = 1, DDI_NN/2
            J2NODE = MYNODE+JPDIF
            IF(J2NODE .GT. DDI_NN) J2NODE = J2NODE-DDI_NN
            J2BAT = (J2NODE-1)*NBATP1+JBATP1
            JOCCBG = INFOCCBAT(1,J2BAT)+1
            JOCCED = INFOCCBAT(1,J2BAT)+INFOCCBAT(2,J2BAT)
C            WRITE(6,*) 'J2BAT=',J2BAT,'JOCCBG=',JOCCBG,'JOCCED=',JOCCED
            CALL TSECND(TIMEC0)
            IF(SMP_ME .EQ. 0)
     *           CALL DDI_GET(D_TA,1,LENT3,JOCCBG,JOCCED,BK)
            CALL DDI_SMP_SYNC()
            CALL TSECND(TIMEC1)
            TIMEC = TIMEC+(TIMEC1-TIMEC0)
            IBATBG = (MYNODE-1)*NBATP1+1
            IBATED = MYNODE*NBATP1
            IF(MOD(DDI_NN,2) .EQ. 0 .AND. JPDIF .EQ. DDI_NN/2) THEN
               IF(MYNODE .LT. J2NODE) THEN
                  IF(JBATP1 .LE. NBATP1C) THEN
                     IBATBG = (MYNODE-1)*NBATP1+1
                     IBATED = (MYNODE-1)*NBATP1+NBATP1C
                  ELSE
                     IBATBG = (MYNODE-1)*NBATP1+NBATP1C+1
                     IBATED = MYNODE*NBATP1
                  END IF
               ELSE
                  IF(JBATP1 .LE. NBATP1C) THEN
                     IBATBG = (MYNODE-1)*NBATP1+NBATP1C+1
                     IBATED = MYNODE*NBATP1
                  ELSE
                     IBATBG = (MYNODE-1)*NBATP1+1
                     IBATED = (MYNODE-1)*NBATP1+NBATP1C
                  END IF
               END IF
            END IF
            CALL DDI_SMP_SYNC()
            DO IBAT = IBATBG, IBATED
               IOCCBG = INFOCCBAT(1,IBAT)+1
               IOCCED = INFOCCBAT(1,IBAT)+INFOCCBAT(2,IBAT)
C          WRITE(6,*) 'IBAT=',IBAT,'IOCCBG=',IOCCBG,'IOCCED=',IOCCED
               CALL TSECND(TIMEC0)
               IF(SMP_ME .EQ. 0)
     *              CALL DDI_GET(D_TA,1,LENT3,IOCCBG,IOCCED,BB)
               CALL DDI_SMP_SYNC()
               CALL TSECND(TIMEC1)
               TIMEC = TIMEC+(TIMEC1-TIMEC0)
C
               CALL RIMP2TEIE2SMP(EIG,BB,BK,Q,E2T,E2S,NAUXBAS,NORB,NOCC,
     *              NVIR,IOCCBG,IOCCED,JOCCBG,JOCCED,IBAT,J2BAT,
     *              TIME4,TIME5,SMP_NP,SMP_ME)
C
               CALL DDI_SMP_SYNC()
            END DO              !IBAT
         END DO                 !JPDIF
C
         J1BAT = (MYNODE-1)*NBATP1+JBATP1
         JOCCBG = INFOCCBAT(1,J1BAT)+1
         JOCCED = INFOCCBAT(1,J1BAT)+INFOCCBAT(2,J1BAT)
         CALL TSECND(TIMEC0)
         IF(SMP_ME .EQ. 0) CALL DDI_GET(D_TA,1,LENT3,JOCCBG,JOCCED,BK)
         CALL DDI_SMP_SYNC()
         CALL TSECND(TIMEC1)
         TIMEC = TIMEC+(TIMEC1-TIMEC0)
         IBATBG = (MYNODE-1)*NBATP1+1
         DO IBAT = IBATBG, J1BAT
            IOCCBG = INFOCCBAT(1,IBAT)+1
            IOCCED = INFOCCBAT(1,IBAT)+INFOCCBAT(2,IBAT)
            CALL TSECND(TIMEC0)
            IF(SMP_ME .EQ. 0) THEN
               IF(IBAT .NE. J1BAT) THEN
                  CALL DDI_GET(D_TA,1,LENT3,IOCCBG,IOCCED,BB)
               ELSE
                  CALL DCOPY(LENT3*INFOCCBAT(2,IBAT),BK,1,BB,1)
               END IF
            END IF
            CALL DDI_SMP_SYNC()
            CALL TSECND(TIMEC1)
            TIMEC = TIMEC+(TIMEC1-TIMEC0)
C
            CALL RIMP2TEIE2SMP(EIG,BB,BK,Q,E2T,E2S,NAUXBAS,NORB,NOCC,
     *           NVIR,IOCCBG,IOCCED,JOCCBG,JOCCED,IBAT,J1BAT,
     *           TIME4,TIME5,SMP_NP,SMP_ME)
C
            CALL DDI_SMP_SYNC()
         END DO                 !IBAT
      END DO                    !JBATP1
C
      CALL DDI_GSUMF(3100,E2T,1)
      CALL DDI_GSUMF(3101,E2S,1)
      E2 = E2T+E2S
C
      IF(MASWRK) WRITE(IW,9999) TIMEC,TIME4,TIME5
      CALL FLSHBF(IW)
      RETURN
C
 9999 FORMAT(/1X,'TIME OF 3/3 INTEGRAL NETWORK COMM.  =    ',F9.1,
     *       /1X,'TIME OF TEI GENERATION              =    ',F9.1,
     *       /1X,'TIME OF MP2 ENERGY ACCUMULATION     =    ',F9.1)
      END
C*MODULE RIMP2_1   *DECK RIMP2E2ACCSMP
      SUBROUTINE RIMP2E2ACCSMP(EIG,BB,BK,Q,INFOCCBAT,E2,E2T,E2S,
     *     NAUXBAS,NORB,NOCC,NVIR,NOCCBAT,
     *     IFILT3,IW,MASWRK,SMP_NP,SMP_ME,USEDM)
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      LOGICAL MASWRK
      LOGICAL USEDM
C
      DOUBLE PRECISION EIG(*),BB(NAUXBAS,NVIR,*),BK(NAUXBAS,NVIR,*),Q(*)
      INTEGER INFOCCBAT(2,NOCCBAT)
C
      INTEGER SMP_NP,SMP_ME
C
      INTEGER D_V,D_T,D_TB
      COMMON /RIMPDD/ D_V,D_T,D_TB
C
      PARAMETER (ZERO=0.0D+00)
C
C     GENERATE 4C-2E ERI FROM 3 INDICES INTERMEDIATE MATRICES
C     AND ACCUMULATE MP2 CORRELATION ENERGY.
C
      TIMER = ZERO
      TIME4 = ZERO
      TIME5 = ZERO
C
      LENT3 = NAUXBAS*NVIR
C
      E2T = ZERO
      E2S = ZERO
      DO JBAT = 1, NOCCBAT
         JOCCBG = INFOCCBAT(1,JBAT)+1
         JOCCED = INFOCCBAT(1,JBAT)+INFOCCBAT(2,JBAT)
         CALL TSECND(TIMER0)
         IF(SMP_ME .EQ. 0) THEN
            IF(.NOT. USEDM) THEN
               DO JOCC = JOCCBG, JOCCED
                  J = JOCC-JOCCBG+1
                  CALL RIMP2T3RD(BK(1,1,J),LENT3,IFILT3,JOCC)
               END DO
            ELSE
               CALL DDI_GET(D_T,1,LENT3,JOCCBG,JOCCED,BK)
            END IF
         END IF
         CALL DDI_SMP_SYNC()
         CALL TSECND(TIMER1)
         TIMER = TIMER+(TIMER1-TIMER0)
         DO IBAT = 1, JBAT
            IOCCBG = INFOCCBAT(1,IBAT)+1
            IOCCED = INFOCCBAT(1,IBAT)+INFOCCBAT(2,IBAT)
            CALL TSECND(TIMER0)
            IF(SMP_ME .EQ. 0) THEN
               IF(IBAT .NE. JBAT) THEN
                  IF(.NOT. USEDM) THEN
                     DO IOCC = IOCCBG, IOCCED
                        I = IOCC-IOCCBG+1
                        CALL RIMP2T3RD(BB(1,1,I),LENT3,IFILT3,IOCC)
                     END DO
                  ELSE
                     CALL DDI_GET(D_T,1,LENT3,IOCCBG,IOCCED,BB)
                  END IF
               ELSE
                  CALL DCOPY(LENT3*INFOCCBAT(2,JBAT),BK,1,BB,1)
               END IF
            END IF
            CALL DDI_SMP_SYNC()
            CALL TSECND(TIMER1)
            TIMER = TIMER+(TIMER1-TIMER0)
C
            CALL RIMP2TEIE2SMP(EIG,BB,BK,Q,E2T,E2S,NAUXBAS,NORB,NOCC,
     *           NVIR,IOCCBG,IOCCED,JOCCBG,JOCCED,IBAT,JBAT,TIME4,TIME5,
     *           SMP_NP,SMP_ME)
C
            CALL DDI_SMP_SYNC()
         END DO                 !IBAT
      END DO                    !JBAT
      E2 = E2S+E2T
C
      IF(MASWRK) WRITE(IW,9999) TIMER,TIME4,TIME5
      CALL FLSHBF(IW)
      RETURN
C
 9999 FORMAT(/1X,'TIME OF 3/3 INTEGRAL READ           =    ',F9.1,
     *       /1X,'TIME OF TEI GENERATION              =    ',F9.1,
     *       /1X,'TIME OF MP2 ENERGY ACCUMULATION     =    ',F9.1)
      END
C*MODULE RIMP2_1   *DECK RIMP2INTTRNSMP
      SUBROUTINE RIMP2INTTRNSMP(LOCSPH,INFOCCABAT,INFOCCBBAT,
     *     NSHELL,NBASIS,NAUXSH,NAUXBAS,NAUXBASD,
     *     NORBA,NORBB,NOCCA,NOCCB,NVIRA,NVIRB,NACORE,NBCORE,
     *     NINTMXA,NINTMXB,NOCCBAT,LENOCCABAT,LENOCCBBAT,IAUXBF,USEDM)
      use mx_limits, only: mxsh,mxgtot,mxatm,mxao
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      LOGICAL GOPARR,DSKWRK,MASWRK
      LOGICAL GONODE,DEBUG
      LOGICAL SPHAUX,USEDM
C
      CHARACTER*1 ADDR(1)
      INTEGER DDI_NP,DDI_ME,DDI_NN,DDI_MY
      INTEGER SMP_NP,SMP_ME
C
      INTEGER D_NT2ABUF,D_NT2BBUF
      INTEGER D_T0,D_T1,D_T2,D_V,D_T3,D_TA,D_ITA,D_ITB
      INTEGER LNT2ABUF,LNT2BBUF
      INTEGER LT0,LT1,LT2,LV,LT3,LTA,LITA,LITB
      INTEGER SHARED_T1,SHARED_T2
C
      INTEGER LOCSPH(*),INFOCCABAT(*),INFOCCBBAT(*)
C
      PARAMETER (MXAUXSH=10000)
      PARAMETER (MXAXGTOT=20000)
C
      COMMON /AUXBAS/ EXAUX(MXAXGTOT),CAUXS(MXAXGTOT),CAUXP(MXAXGTOT),
     *                CAUXD(MXAXGTOT),CAUXF(MXAXGTOT),CAUXG(MXAXGTOT),
     *                CAUXH(MXAXGTOT),CAUXI(MXAXGTOT),
     *                KAUXST(MXAUXSH),KAUXAT(MXAUXSH),KAUXTY(MXAUXSH),
     *                KAUXNG(MXAUXSH),KAUXLO(MXAUXSH),KAUXMI(MXAUXSH),
     *                KAUXMX(MXAUXSH),NAUXSHX
      COMMON /FMCOM / X(1)
      COMMON /IJPAIR/ IA(MXAO)
      COMMON /INFOA / NAT,ICH,MUL,NUM,NQMT,NE,NA,NB,
     *                ZAN(MXATM),C(3,MXATM),IAN(MXATM)
      COMMON /IOFILE/ IR,IW,IP,IJK,IPK,IDAF,NAV,IODA(950)
      COMMON /NSHEL / EX(MXGTOT),CS(MXGTOT),CP(MXGTOT),CD(MXGTOT),
     *                CF(MXGTOT),CG(MXGTOT),CH(MXGTOT),CI(MXGTOT),
     *                KSTART(MXSH),KATOM(MXSH),KTYPE(MXSH),KNG(MXSH),
     *                KLOC(MXSH),KMIN(MXSH),KMAX(MXSH),NSHELLX
      COMMON /PAR   / ME,MASTER,NPROC,IBTYP,IPTIM,GOPARR,DSKWRK,MASWRK
      COMMON /RUNOPT/ RUNTYP,EXETYP,NEVALS,NGLEVL,NHLEVL
      COMMON /WFNOPT/ SCFTYP,VBTYP,DFTYPE,TDDFTYP,CITYP,CCTYP,
     *                MPLEVL,MPCTYP
C
      COMMON /RIMPFI/ IFILV,IFILT2A,IFILT3A,IFILT2B,IFILT3B
C
      INTEGER D_VD,D_TAD,D_TBD
      COMMON /RIMPDD/ D_VD,D_TAD,D_TBD
C
      DATA CHECK    /8HCHECK   /
      DATA RHF      /8HRHF     /
      DATA UHF      /8HUHF     /
C
C     SUB DRIVER FOR INTEGRAL TRANSFORMATION OF 3C-2E ERIS (PQ|L).
C     RIMP2INTTR1: ERI EVALUATION AND FIRST 1/3 AND 2/3 TRANSFORMATION
C     RIMP2INTTR2: 3/3 TRANSFORMATION
C
      CALL DDI_NPROC(DDI_NP,DDI_ME)
      CALL DDI_NNODE(DDI_NN,DDI_MY)
      CALL DDI_SMP_NPROC(SMP_NP,SMP_ME)
      GONODE = DDI_NN .GT. 1
C
      SPHAUX = .FALSE.
      IF(IAUXBF .EQ. 1) SPHAUX = .TRUE.
C
C     CHECK HIGHEST ANGLAR MOMENTUM OF ATOMIC ORBITAL AND
C     AUXILIARY BASIS FUNCTIONS.
C
      KANG = 0
      DO N = 1, NSHELL
         IF(KTYPE(N)  .GT. KANG) KANG = KTYPE(N)
      END DO
      DO N = 1, NAUXSH
         IF(KAUXTY(N) .GT. KANG) KANG = KAUXTY(N)
      END DO
      LMAX = KANG-1
                    NANGM =  4
      IF(LMAX.EQ.2) NANGM =  6
      IF(LMAX.EQ.3) NANGM = 10
      IF(LMAX.EQ.4) NANGM = 15
      IF(LMAX.EQ.5) NANGM = 21
      IF(LMAX.EQ.6) NANGM = 28
                 MAXG = NANGM**3
C
C     ALLOCATE SHARED MEMORY FOR BATCH INFORMATION OF
C     2/3 TRANSFORMED INTEGRALS TO BE STORED IN DISKS.
C
      CALL DDI_SMP_CREATE(2*NOCCBAT,D_NT2ABUF)
C     DETERMINE OFFSETS FOR SHARED MEMORY ARRAYSD
      CALL DDI_SMP_OFFSET(D_NT2ABUF,ADDR,LNT2ABUF)
      LNT2ABUF = LNT2ABUF+1
      IF(SCFTYP .EQ. UHF) THEN
         CALL DDI_SMP_CREATE(2*NOCCBAT,D_NT2BBUF)
C        DETERMINE OFFSETS FOR SHARED MEMORY ARRAYSD
         CALL DDI_SMP_OFFSET(D_NT2BBUF,ADDR,LNT2BBUF)
         LNT2BBUF = LNT2BBUF+1
      END IF
C
      CALL DDI_SMP_SYNC()
C
C     SPECIFY MATRIX SIZES
C
      NBF2 = NBASIS*(NBASIS+1)/2
      NBF3 = NBASIS*NBASIS
C
C     ALLOCATE REPLICATED MEMORY FOR VEC
C
      CALL VALFM(LOADFM)
      LVECA  = LOADFM + 1
      LAST   = LVECA  + NBF3
      IF(SCFTYP .EQ. UHF) THEN
         LVECB  = LAST
         LAST   = LVECB  + NBF3
      END IF
      NEEDV = LAST-LOADFM-1
      CALL GETFM(NEEDV)
C
C     READ MOLECULAR ORBITALS
C
      IF(EXETYP .NE. CHECK) THEN
         CALL DAREAD(IDAF,IODA,X(LVECA),NBF3,15,0)
         NORB = NORBA+NACORE
         MAXC = IDAMAX(NBASIS*NORB,X(LVECA),1)
         IF(ABS(X(LVECA+MAXC-1)).GT.1.0D+02) THEN
            MAXM = 1 + MAXC/NBASIS
            MAXA = MAXC - NBASIS*(MAXM-1)
            IF(MASWRK) WRITE(IW,9030) ABS(X(LVECA+MAXC-1)),MAXA,MAXM
         END IF
         IF(SCFTYP .EQ. UHF) THEN
            CALL DAREAD(IDAF,IODA,X(LVECB),NBF3,19,0)
            NORB = NORBB+NBCORE
            MAXC = IDAMAX(NBASIS*NORB,X(LVECB),1)
            IF(ABS(X(LVECB+MAXC-1)).GT.1.0D+02) THEN
               MAXM = 1 + MAXC/NBASIS
               MAXA = MAXC - NBASIS*(MAXM-1)
               IF(MASWRK) WRITE(IW,9030) ABS(X(LVECB+MAXC-1)),MAXA,MAXM
            END IF
         END IF
      END IF
C
C     ALLOCATE MEMORY FOR AO TRANSFORMATIONS
C     (CARTESIAN->SPHERICAL HARMONIC)
C
      CALL VALFM(LOADFM)
      LS     = LOADFM + 1
      LQ     = LS     + NBF2
      LWRK   = LQ     + NBF3
      LMOLAB = LWRK   + NBASIS
      LMOIRP = LMOLAB + NBASIS
      LMODEG = LMOIRP + NBASIS
      LAST   = LMODEG + NBASIS
      NEEDS  = LAST   - LOADFM+1
      CALL GETFM(NEEDS)
C
C     TRANSFORM CARTESIAN TO SPHERICAL HARMONICS
C
      IF(EXETYP .NE. CHECK) THEN
         CALL DAREAD(IDAF,IODA,X(LS),NBF2,12,0)
         CALL DAREAD(IDAF,IODA,X(LQ),NBF3,45,0)
         NORB = NORBA+NACORE
         CALL TRFSYM(X(LMOLAB),X(LMOIRP),X(LMODEG),X(LQ),X(LS),
     *        X(LVECA),X(LWRK),IA,NQMT,NBASIS,NORB,NBASIS)
         IF(SCFTYP .EQ. UHF) THEN
            CALL DAREAD(IDAF,IODA,X(LQ),NBF3,45,0)
            NORB = NORBB+NBCORE
            CALL TRFSYM(X(LMOLAB),X(LMOIRP),X(LMODEG),X(LQ),X(LS),
     *           X(LVECB),X(LWRK),IA,NQMT,NBASIS,NORB,NBASIS)
         END IF
      END IF
C
C     FREE REPLICATED MEMORY
C
      CALL RETFM(NEEDS)
C
C     REMOVE CORE MOLECULAR ORBITALS
C
      IF(EXETYP .NE. CHECK) THEN
         CALL RIMP2SHIFTORB(X(LVECA),NBASIS,NORBA,NACORE)
         IF(SCFTYP .EQ. UHF)
     *        CALL RIMP2SHIFTORB(X(LVECB),NBASIS,NORBB,NBCORE)
      END IF
C
C     ALLOCATE MEMORY FOR 1/3 AND 2/3 INDEX TRANSFORMATIONS
C
      CALL VALFM(LOADFM)
      LCC     = LOADFM  + 1
      LGHONDO = LCC     + 9
      LTL     = LGHONDO + MAXG
      LW      = LTL     + NANGM*NANGM
      LT2BUFF = LW      + NANGM*NANGM
      LAST    = LT2BUFF + MAX(NOCCA*NVIRA,NOCCB*NVIRB)
      NEED1   = LAST-LOADFM-1
      IF(MASWRK) WRITE(IW,9010) NEEDV+NEED1
      CALL FLSHBF(IW)
      CALL GETFM(NEED1)
C
C     ESTIMATE SHARED MEMORY
C
      LENT0 = NBF3*NANGM
      LENT1 = MAX(NOCCA*NBASIS,NOCCB*NBASIS,NINTMXA,NINTMXB)
      LENT2 = MAX(NOCCA*NVIRA,NOCCB*NVIRB)
      SHARED_T1 = LENT0+LENT1+LENT2
      GBYTES = 8*SHARED_T1/(1024.0D+00**3)
      IF(MASWRK) WRITE(IW,9020) 1,SHARED_T1,GBYTES
C
C     ALLOCATE SHARED MEMORY
C
      CALL DDI_SMP_CREATE(LENT0,D_T0)
      CALL DDI_SMP_CREATE(LENT1,D_T1)
      CALL DDI_SMP_CREATE(LENT2,D_T2)
C     DETERMINE OFFSETS FOR SHARED MEMORY ARRAYS
      CALL DDI_SMP_OFFSET(D_T0,ADDR,LT0)
      CALL DDI_SMP_OFFSET(D_T1,ADDR,LT1)
      CALL DDI_SMP_OFFSET(D_T2,ADDR,LT2)
C
      LT0 = LT0+1
      LT1 = LT1+1
      LT2 = LT2+1
C
      CALL DDI_SMP_SYNC()
C
C     PERFORM 1/3 AND 2/3 INDEX TRANSFORMATIONS
C
      IF(EXETYP .NE. CHECK) THEN
         IF(SCFTYP .EQ. RHF) THEN
            CALL RIMP2INTTR1SMP(X(LVECA),X(LCC),
     *           ADDR(LT0),ADDR(LT1),ADDR(LT2),X(LT2BUFF),
     *           X(LGHONDO),X(LTL),X(LW),LOCSPH,
     *           INFOCCABAT,ADDR(LNT2ABUF),
     *           NSHELL,NBASIS,NAUXSH,
     *           NOCCA,NVIRA,NINTMXA,NOCCBAT,
     *           IFILT2A,IW,SPHAUX,USEDM,
     *           DDI_NN,DDI_MY,SMP_NP,SMP_ME)
         ELSE IF(SCFTYP .EQ. UHF) THEN
            CALL RIUMP2INTTR1SMP(X(LVECA),X(LVECB),X(LCC),
     *           ADDR(LT0),ADDR(LT1),ADDR(LT2),X(LT2BUFF),
     *           X(LGHONDO),X(LTL),X(LW),LOCSPH,
     *           INFOCCABAT,INFOCCBBAT,ADDR(LNT2ABUF),ADDR(LNT2BBUF),
     *           NSHELL,NBASIS,NAUXSH,
     *           NOCCA,NOCCB,NVIRA,NVIRB,NINTMXA,NINTMXB,NOCCBAT,
     *           IFILT2A,IFILT2B,IW,SPHAUX,USEDM,
     *           DDI_NN,DDI_MY,SMP_NP,SMP_ME)
         END IF
      END IF
      CALL DDI_SYNC(5132)
C
C     DESTROY SHARED-MEMORY ARRAYS
C
      CALL DDI_SMP_DESTROY(D_T0)
      CALL DDI_SMP_DESTROY(D_T1)
      CALL DDI_SMP_DESTROY(D_T2)
      CALL DDI_SMP_SYNC()
C
C     FREE REPLICATED MEMORY FOR 1/3 AND 2/3 TRANSFORMATIONS
C     FREE REPLICATED MEMORY FOR VECTORS
C
      CALL RETFM(NEED1)
      CALL RETFM(NEEDV)
C
C          THIS IS A GOOD PLACE TO LEAVE SOME DEBUGGING CODE,
C          BUT NOT TURNED ON, SINCE THE PRINT FILE IS ALWAYS 6.
C
      DEBUG = IW.LT.0  .AND.  USEDM
      IF(.NOT.DEBUG) GO TO 500
C
C          THE FOLLOWING PRINTS THE ALPHA T2 DISTRIBUTED MATRIX.
C          IT WOULD BE EASY TO VERIFY THE BETA MATRIX IF YOU WISH.
C
      IF(MASWRK) THEN
         WRITE(IW,8013) D_TAD,NAUXBAS,NVIRA,NOCCA
C
         CALL VALFM(LOADFM)
         LBUF = LOADFM + 1
         LAST = LBUF   + NVIRA*NOCCA
         NEEDDBG = LAST - LOADFM - 1
         CALL GETFM(NEEDDBG)
C                SHOW THE SUM OF ONLY A FEW ROWS
         DO LAUX = 1,MIN(10,NAUXBAS)
            IBG=NVIRA*(LAUX-1)+1
            IED=NVIRA*LAUX
            CALL DDI_GET(D_TAD,IBG,IED,1,NOCCA,X(LBUF))
            CALL MTXCHECK(X(LBUF),NVIRA,NVIRA,NOCCA,1,ABSSUM)
            WRITE(IW,8015) LAUX,ABSSUM
         ENDDO
         CALL RETFM(NEEDDBG)
C
         CALL VALFM(LOADFM)
         LBUF = LOADFM + 1
         LAST = LBUF   + NAUXBAS*NVIRA
         NEEDDBG = LAST - LOADFM - 1
         CALL GETFM(NEEDDBG)
         LENCOL = NAUXBAS*NVIRA
         DO I=1,NOCCA
            CALL DDI_GET(D_TAD,1,LENCOL,I,I,X(LBUF))
            CALL MTXCHECK(X(LBUF),LENCOL,LENCOL,1,1,ABSSUM)
            WRITE(IW,8017) I,ABSSUM
         ENDDO
         CALL RETFM(NEEDDBG)
      END IF
      CALL DDI_SYNC(5232)
 8013 FORMAT(1X,'DM=',I4,' WITH ROWS NAUXBAS=',I6,' * NVIRA=',I5,
     *          ' AND COLS NOCCA=',I5)
 8015 FORMAT(1X,'HAS    ROW=',I5,'''S ABSOLUTE VALUE SUM =',F22.8)
 8017 FORMAT(1X,'HAS COLUMN=',I5,'''S ABSOLUTE VALUE SUM =',F22.8)
C
C     ESTIMATE SHARED MEMORY FOR 3RD INDEX TRANSFORMATION
C
  500 CONTINUE
      IF(SCFTYP .EQ. RHF) THEN
         L1 = NAUXBAS*NAUXBAS
         L2 = NAUXBAS*NVIRA
         L3 = NAUXBAS*NVIRA*LENOCCABAT
         L4 = NINTMXA
         L5 = NAUXBAS*NINTMXA
      ELSE IF(SCFTYP .EQ. UHF) THEN
         L1 = NAUXBAS*NAUXBAS
         L2 = NAUXBAS*MAX(NVIRA,NVIRB)
         L3 = NAUXBAS*MAX(NVIRA,NVIRB)*MAX(LENOCCABAT,LENOCCBBAT)
         L4 = MAX(NINTMXA,NINTMXB)
         L5 = NAUXBAS*MAX(NINTMXA,NINTMXB)
      END IF
      IF(GONODE) THEN
         SHARED_T2 = L1+L3+MAX(L2,L4,L5)+L5+2*NAUXBAS
      ELSE
         SHARED_T2 = L1+L3+MAX(L2,L4,L5)
      END IF
      GBYTES = 8*SHARED_T2/(1024.0D+00**3)
      IF(MASWRK) WRITE(IW,9020) 2,SHARED_T2,GBYTES
C
C     ALLOCATE SHARED MEMORY
C
      CALL DDI_SMP_CREATE(L1,D_V)
      CALL DDI_SMP_CREATE(L3,D_T2)
      CALL DDI_SMP_CREATE(MAX(L2,L4,L5),D_T3)
      IF(GONODE) THEN
         CALL DDI_SMP_CREATE(L5,D_TA)
         CALL DDI_SMP_CREATE(NAUXBAS,D_ITA)
         CALL DDI_SMP_CREATE(NAUXBAS,D_ITB)
      END IF
C     DETERMINE OFFSETS FOR SHARED MEMORY ARRAYS
      CALL DDI_SMP_OFFSET(D_V,ADDR,LV)
      CALL DDI_SMP_OFFSET(D_T2,ADDR,LT2)
      CALL DDI_SMP_OFFSET(D_T3,ADDR,LT3)
      IF(GONODE) THEN
         CALL DDI_SMP_OFFSET(D_TA,ADDR,LTA)
         CALL DDI_SMP_OFFSET(D_ITA,ADDR,LITA)
         CALL DDI_SMP_OFFSET(D_ITB,ADDR,LITB)
      END IF
C
      LV  = LV+1
      LT2 = LT2+1
      LT3 = LT3+1
      IF(GONODE) THEN
         LTA  = LTA+1
         LITA = LITA+1
         LITB = LITB+1
      END IF
C
      CALL DDI_SMP_SYNC()
C
C     PERFORM 3/3 INDEX TRANSFORMATION
C     MULTIPLY CHOLESKY DECOMPOSED MATRIX OF V^(-1) MATRIX
C
      IF(EXETYP .NE. CHECK) THEN
         IF(GONODE .AND. .NOT. USEDM) THEN
            CALL RIMP2INTTR2PSMP(ADDR(LV),ADDR(LT2),ADDR(LT3),ADDR(LTA),
     *           INFOCCABAT,ADDR(LITA),ADDR(LITB),ADDR(LNT2ABUF),
     *           NAUXBAS,NAUXBASD,NVIRA,NINTMXA,
     *           NOCCBAT,IFILV,IFILT2A,IFILT3A,IW,
     *           DDI_NN,DDI_MY,SMP_NP,SMP_ME)
            IF(SCFTYP .EQ. UHF) THEN
               CALL RIMP2INTTR2PSMP(ADDR(LV),ADDR(LT2),ADDR(LT3),
     *              ADDR(LTA),
     *              INFOCCBBAT,ADDR(LITA),ADDR(LITB),ADDR(LNT2BBUF),
     *              NAUXBAS,NAUXBASD,NVIRB,NINTMXB,
     *              NOCCBAT,IFILV,IFILT2B,IFILT3B,IW,
     *              DDI_NN,DDI_MY,SMP_NP,SMP_ME)
            END IF
         ELSE
            CALL RIMP2INTTR2SMP(ADDR(LV),ADDR(LT2),ADDR(LT3),INFOCCABAT,
     *           ADDR(LNT2ABUF),
     *           NAUXBAS,NAUXBASD,NVIRA,NINTMXA,
     *           NOCCBAT,IFILV,IFILT2A,IFILT3A,IW,
     *           DDI_NN,DDI_MY,SMP_NP,SMP_ME,USEDM,D_VD,D_TAD)
            IF(SCFTYP .EQ. UHF) THEN
               CALL RIMP2INTTR2SMP(ADDR(LV),ADDR(LT2),ADDR(LT3),
     *              INFOCCBBAT,ADDR(LNT2BBUF),
     *              NAUXBAS,NAUXBASD,NVIRB,NINTMXB,
     *              NOCCBAT,IFILV,IFILT2B,IFILT3B,IW,
     *              DDI_NN,DDI_MY,SMP_NP,SMP_ME,USEDM,D_VD,D_TBD)
            END IF
         END IF
      END IF
C
C     DESTROY SHARED-MEMORY ARRAYS
C
      CALL DDI_SMP_DESTROY(D_V)
      CALL DDI_SMP_DESTROY(D_T2)
      CALL DDI_SMP_DESTROY(D_T3)
      IF(GONODE) THEN
         CALL DDI_SMP_DESTROY(D_TA)
         CALL DDI_SMP_DESTROY(D_ITA)
         CALL DDI_SMP_DESTROY(D_ITB)
      END IF
C
C     DESTROY SHARED-MEMORY ARRAYS
C
      CALL DDI_SMP_DESTROY(D_NT2ABUF)
      IF(SCFTYP .EQ. UHF) CALL DDI_SMP_DESTROY(D_NT2BBUF)
C
      CALL DDI_SYNC(5133)
      RETURN
C
 9010 FORMAT(/1X,'REPLICATED MEMORY REQUIRED FOR 1/3 TRANSFORMATION=',
     *           I12,' WORDS')
 9020 FORMAT( 1X,'SHARED MEMORY REQUIRED FOR ',I1,
     *           '/3 TRANSFORMATION    =',I12,' WORDS'/
     *       50X,'=',F12.2,' GBYTES/NODE')
 9030 FORMAT(/1X,'*** WARNING: THE MAXIMUM LCAO COEF=',F15.6,
     *           ', FOR AO',I6,' IN MO=',I6,','/
     *        1X,'EXCEEDS 100.  ADDITIONAL INPUTS MAY BE REQUIRED TO',
     *           ' OBTAIN GOOD MP2 ACCURACY:'/
     *        1X,' $CONTRL ICUT=10 OR 11'/
     *        1X,' $SCF    CONV=2.5D-7 FDIFF=.FALSE.'/)
      END