C*MODULE STUBCC3 DECK OPEN_CCSD3A_DRIVER
C> @brief Stub to allow optional build
C>
C> @author Sarom Leang
       SUBROUTINE OPEN_CCSD3A_DRIVER(IO,N1,N2,N3,N0,NFRV,MAXIT,
     *               ITOL,MULT,EREF,ECOR,M1,M2,
     *               NFT825,NFT843,NFT820,NFT821,NFT822,NFT823,NFT826,
     *               NFT827,NFT828,NFT829,NFT830,NFT833,NFT831,NFT832,
     *               NFT834,NFT835,NFT836,NFT837,NFT838,NFT839,NFT848)
C
        INTEGER,ALLOCATABLE :: ICOE(:)
C
        LOGICAL IFRHF
        REAL*8 SHIFT,EREF,ECOR
        INTEGER MARG,NARG,IERR
        PARAMETER (MARG=20)
        CHARACTER*100 ARG(0:MARG)
        CHARACTER*100 INNAME,OUTNAME

        INTEGER TYPARG(0:MARG)
        INTEGER NFT825,NFT843,NFT820,NFT821,NFT822,NFT823,NFT826
        INTEGER NFT827,NFT828,NFT829,NFT830,NFT833,NFT831,NFT832
        INTEGER NFT834,NFT835,NFT836,NFT837,NFT838,NFT839,NFT848
        CHARACTER LINE*100,INPNAME*100,COMMAND*256
        INTEGER INP,IO,A,B,C,D
        PARAMETER(INP=12,ICR1=101)
        REAL*8,ALLOCATABLE:: FAHH(:,:)
        REAL*8,ALLOCATABLE:: FAHP(:,:)
        REAL*8,ALLOCATABLE:: FAPP(:,:)
        REAL*8,ALLOCATABLE:: FBHH(:,:)
        REAL*8,ALLOCATABLE:: FBHP(:,:)
        REAL*8,ALLOCATABLE:: FBPP(:,:)
        REAL*8,ALLOCATABLE:: VAHHHH(:,:,:,:)
        REAL*8,ALLOCATABLE:: VAHHHP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VAHHPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VAHPHP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VAHPPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBHHHH(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBHHHP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBHHPH(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBHHPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBHPHP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBHPPH(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBPHPH(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBHPPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBPHPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VCHHHH(:,:,:,:)
        REAL*8,ALLOCATABLE:: VCHHHP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VCHHPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VCHPHP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VCHPPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VAAPPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBAPPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBPAPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VCAPPP(:,:,:,:)
        REAL*8,ALLOCATABLE:: VBPPP(:,:,:)
        LOGICAL RESTART
        END

C*MODULE STUBCC3 DECK COUNT_MEM_CCSD3A
C> @brief Stub to allow optional build
C>
C> @author Sarom Leang
      SUBROUTINE COUNT_MEM_CCSD3A(N0,N1,N2,N3,M1,M2,COUNT_MEM)
      IMPLICIT NONE
      INTEGER NOACT, NUACT
      INTEGER N0,N1,N2,N3,M1,M2
      INTEGER K1,K2,K3,K4,K5,K6,K7,K8,K9,K0
      INTEGER K3A
      INTEGER K3B1,K3B2,K3B3,K3B4
      INTEGER K3C1,K3C2,K3C3,K3C4
      INTEGER K3D
      INTEGER T_SIZE
      INTEGER COUNT_MEM
      END

C*MODULE STUBCC3 DECK DEAEOMDIP_FOCK
C> @brief Stub to allow optional build
C>
C> @author Jun Shen
      SUBROUTINE  DEAEOMDIP_FOCK(EREF,NREF)
      IMPLICIT NONE
      INTEGER NREF
      DOUBLE PRECISION EREF
      END

C*MODULE STUBCC3 DECK DEAEOMDIP_HBAR
C> @brief Stub to allow optional build
C>
C> @author Jun Shen
      SUBROUTINE DEAEOMDIP_HBAR(IO,NOA,NOB,NUA,EREF,ENRG)
      IMPLICIT NONE
      INTEGER IO,NOA,NOB,NUA
      DOUBLE PRECISION EREF,ENRG
      END

C*MODULE STUBCC3 DECK DRDEAEOMDIP
C> @brief Stub to allow optional build
C>
C> @author Jun Shen
      SUBROUTINE DRDEAEOMDIP(BESTEOM,IW,NOA,NOB,NUA,EREF,ENRG,CCTYP)
      IMPLICIT NONE
      INTEGER IW,NOA,NOB,NUA
      DOUBLE PRECISION BESTEOM,EREF,ENRG,CCTYP
      END
