C 26 Sep 20 - DD  - fix memory allocation in SETFM
c 22 Oct 14 - DGF - changes for FMO 5.1
C 19 Mar 14 - MWS - TSECND: spell wall timer as XQTIME for Linux/Mac
C 27 Apr 12 - MWS - provide MEMGET/MEMREL for HP-UX
C 28 DEC 11 - DGF - REDUCE I/O BY NOT FLUSHING
C 15 APR 11 - MWS - ADD SIMULATION OF RANDOM_NUMBER INTRINSIC
C 13 MAY 10 - SS  - ADD *W32 / *W64 WINDOWS SUPPORT
C 10 MAY 10 - AA  - 3 ROUTINES TO CUSTOMIZE SERIAL EXEC. MATRIX SIZES
C 18 JUL 08 - MWS - VNAN: NEW ROUTINE TO CREATE BAD VALUES
C 14 FEB 07 - AA  - ADD "FGE" ROUTINE TO GET ENV. VALUES FROM A DISKFILE
C 22 DEC 06 - MWS,SK - LINUX PORTS *F2C,*AMD,*ITA RENAMED *L32,*L64,*INT
C 22 DEC 06 - DGF - ADD TIMING PRINT-OUT ON SLAVES
C 10 JUL 06 - SK,MWS - TSECND: CHANGE *AMD TIMING TO USUAL LINUX WAY
C 17 JAN 06 - RAK - ADD FLUSHONWRITE ROUTINE FOR IBM/AIX
C 19 NOV 05 - TJP - ADD *XT3 CODE FOR CRAY XT3
C  5 JUL 05 - MWS - SELECT NEW ATOM,BASIS,EFP,PCM,DAF DIMENSIONS
C  1 JUN 05 - MWS - FLSHBF: IBM/AIX SHOULD PASS 4 BYTE ARG TO FLUSH_
C  5 FEB 05 - MWS - FLSHBF: ADD ITANIUM CODING
C  7 SEP 04 - MWS - PAD COMMON BLOCK INTFIL
C 23 JUL 03 - SK,HU,TJP - INCLUDE 64 BIT AMD CHIP VERSION (*AMD)
C  4 NOV 03 - TJP - INCLUDE ROUTINE FOR EFFECTIVE VECTOR LENGTH
C  3 SEP 03 - MWS - TSECND: *ITA TIMING CALLS FIXED
C  3 JUL 03 - JMM - SUPPRESS PRINTING FOR MONTE CARLO JOBS
C 26 MAR 03 - TJP - ADD *CX1 CODE FOR CRAY-X1
C 28 JAN 03 - MWS - ADAPTATIONS FOR A 64 BIT SUN VERSION
C 12 DEC 02 - YA  - GETFM: LET ANY NODE PRINT MEMORY ALLOCATION ERROR
C  7 AUG 02 - ZK  - USE FORTRAN LIBRARY ROUTINES FOR THE HP VERSION
C 20 JUN 02 - FPA - ADD *ITA ITANIUM LINUX VERSION
C 17 APR 02 - KRG - REMOVE A STOP STATEMENT
C 16 FEB 02 - MWS - TSECND,TMDATE: CHANGE IBM TIMING CALLS
C 24 JAN 02 - MWS - ABRT: STALL 2 SECONDS TO ALLOW FOR OUTPUT FLUSH
C  7 DEC 01 - STE - ADD *WIN LINES FOR WIN32 VERSION
C  8 OCT 01 - MWS - PARSET: OMIT BALTYP OVERRIDES, UPDATE ITRFAO VALS
C  6 SEP 01 - MWS - FLSHBF: DIGITAL CHANGED
C 10 JUL 01 - MWS - TMDATE: ADD 1900 TO HP'S YEAR VALUE
C  1 MAY 00 - MWS - CHANGES TO MATCH MODIFIED ZUNIX.C
C 25 MAR 00 - MWS - REMOVE BRIAN'S GO AT A SEPARATE ALPHA LINUX VERSION
C 25 SEP 99 - MWS - BEGING: REMOVE ZMIPS CALL
C 29 AUG 99 - BSD - ADD STATIC MEMORY ALPHA LINUX CODE
C  6 JUN 99 - MWS - ADD CALLING ARGS TO DDI_PBEG AND DDI_PEND
C 12 NOV 98 - MWS - T3D TO T3E, DEL CONVEX (CVX), LOGSHF, DEC=64 BIT
C 22 APR 98 - MWS - ENDING: AVOID FINAL FLOATING PT. WARNINGS ON SUN
C 13 APR 98 - AJL - FLUSH OUTPUT ON FUJITSU
C 27 FEB 98 - AR,AR - CORRECT FUJITSU LOGICAL FUNCTIONS, CHANGE TIMING
C  6 JAN 98 - MY  - INCLUDE HITACHI SR VERSION
C 28 SEP 97 - MWS - DEPRECATE MANY OLD MACHINES. NAMELY, WE DROP SUPPORT
C                   FOR *ALL, *AMD, *APO, *CEL, *INT, *KSR, *STR, *TMC
C  8 SEP 97 - MWS - CONVERT PARALLEL CALLS FROM TCGMSG TO DDI
C  2 SEP 97 - MWS - ABRT: INSERT PROPER F2C CODE
C 24 JUL 97 - KRG - TIMIT: CHANGE FORMATTING TO 2 LINES
C 22 JUL 97 - DGF - ADD BIT OPERATIONS LOGNOT, LOGOR, LOGSHF, LOGXOR
C 19 FEB 97 - FPR - TMDATE: DECLARATION FOR HP
C 20 DEC 96 - HPP - BEGING,TSECND: T3E IN BANNER, ADD CPU TIMING
C 12 MAY 96 - MWS - PARSET,MSGSET: CHANGES FOR MPI INTERFACE
C 24 MAY 95 - MWS - PARSET: ASSIGN PARALLEL AO TRANSFORMATION STORAGE
C 29 MAR 95 - MK  - AIX'S XLF VERSION 3 CAN FLUSH_
C  6 MAR 95 - KPG - TSECND: USE AN ACTUAL TIMING CALL
C 17 NOV 94 - MWS - ADD TEXIT,TIMIT TO CONSOLIDATE ALL TIMING CODE
C 11 NOV 94 - MWS - REMOVE A FEW FTNCHEK WARNINGS
C 28 OCT 94 - MWS - BEGING: USE XDR UNTIL AFTER $SYSTEM IS READ
C 23 AUG 94 - ML  - INCLUDE CRAY-T3D VERSION
C 10 AUG 94 - MWS - INCREASE NUMBER OF DAF RECORDS
C 19 JUL 94 - MWS - ADD ROUTINE ASKVEC
C 19 JUN 94 - DM  - TSECND: CHANGE HP TIMING CALL
C  4 APR 94 - MWS - MSGSET: XDR USAGE IS OPTIONAL
C 18 MAR 94 - MM  - TSECND: CONVEX CPUTIME IS SINGLE PRECISION
C 29 DEC 93 - PVZ - ADDED F2C OPTION FOR F2C/GCC COMPILATION
C 31 SEP 93 - GJA - ADD FLUSH FOR AIX
C 24 SEP 93 - JF  - ADD *NEC LINES FOR NEC
C 20 SEP 93 - WS,JAB - ADD *KSR LINES
C  7 SEP 93 - SS  - BEGING: CM-5 NEEDS MODE OF STDERR RESET
C 19 AUG 93 - RHN - TMDATE: CHANGE HP TIME STAMP CALLS
C 24 MAY 93 - NAN - MSGSET: DON'T USE MESSAGE MASKS FOR CRAY
C 10 FEB 93 - TLW - THINKING MACHINES VERSION
C 31 OCT 92 - MWS - TMDATE: FIX COUNTING LEAP YEARS FOR AIX
C 20 JUN 92 - DP,FS,CJ,TH - HP9000-7X0 TIMING CODE
C 17 APR 92 - TLW,MWS - ADD PARSET, OTHER IPSC/860 MODIFICATIONS
C  7 APR 92 - MS  - SETFM: USE MALLOPT(%VAL(1),%VAL(0)) FOR AIX 3.1.5
C 26 MAR 92 - TLW - MESSAGE MASKS DEFINED IN ROUTINE MSGSET
C  2 MAR 92 - TLW - FLSHBF: ONLY MASTER WORK
C 30 JAN 92 - TLW - TMDATE: FIX PARALLEL CALLS
C 29 JAN 92 - TLW - BEGING: PUT IN PARALLEL INITIALIZATION;
C                   ENDING: PUT IN PARALLEL CLEANUP
C 11 JAN 92 - TLW - ABRT: RUN IN PARALLEL
C  8 JAN 92 - TLW - MAKE WRITES PARALLEL; ADD COMMON PAR
C  1 JAN 92 - MWS - FLSHBF: UNICOS VERSION 6 HAS FLUSH CALL
C 18 DEC 91 - MWS - PUT IN FRED SENESE'S HP CODE
C 18 NOV 91 - NM  - ABRT: NO ARGUMENT IN AIX CALL TO ABORT
C  6 SEP 91 - JAB - ADD INT FOR INTEL IPSC/860 RUNNING NX/2
C 28 AUG 91 - RHN - ADD FUJITSU UXP/M SUPPORT
C 20 JUN 91 - MWS - CHANGE IN TMDATE'S DECSTATION CODE FOR F77 3.0
C 15 FEB 91 - TLW - PRAGMA ADDED TO ABRT FOR AIX/370
C  4 FEB 91 - TLW - ABRT: ADD IF ICORFL LINES
C 29 JAN 91 - TLW - ABRT: ADD COMMON MACHSW AND FLUSHES
C  8 DEC 90 - UK  - TMDATE: FIX LEAP YEAR COMPUTATION FOR AIX
C 15 SEP 90 - MWS - MOVE UPCASE BACK INTO FRFMT SECTION
C  1 AUG 90 - MWS - AIX CHANGED TO USE DYNAMIC MEMORY
C 20 JUN 90 - FRJ - TSECND: CONVEX CPUTIME IS DOUBLE PRECISION
C  1 MAY 90 - STE - BEGING: ENABLE FP EXCEPT. ON MIPS BASED SYSTEMS
C  5 APR 90 - JHJ - ADD UPCASE ROUTINE
C 20 MAR 90 - MG  - ADD ETIME SIMULATOR FOR 68000 BASED APOLLOS.
C 23 FEB 90 - MWS - DECSTN MEMORY ALLOCATION MUST HAVE EXTERNAL LOC,
C                   FLUSH PUNCH BUFFER IN BIGFM.
C  6 FEB 90 - MWS - SETFM: LIMFM SHOULD BE MEMLIM, NOT MEMAVL
C 22 JAN 90 - MWS - UNICOS VERSION, WITH DYNAMIC MEMORY
C 16 JAN 90 - MWS - SETFM: EXPLANATORY COMMENTS, DYNAMIC MEMORY ALA
C                   STEVE ELBERT FOR ALL,ARD,CEL,CVX,SUN VERSIONS.
C  3 JAN 90 - STE - DYNAMIC MEMORY SUPPORT FOR DEC, SGI VERSIONS
C 29 DEC 89 - JAM - CONVEX CAN FLUSH BUFFERS TOO.
C 22 SEP 89 - MWS - ADD STEVE'S APO, SGI, STR, SUN VERSIONS
C 21 SEP 89 - STE - MOVE LOGAND FROM MTHLIB TO HERE
C 21 AUG 89 - CFJ - ABRT CALLS TRACEBACK FOR CONVEX VERSION
C 18 AUG 89 - MWS - ADD IBM AIX SUPPORT
C 11 JUL 89 - STE - ADD DECSTATION SUPPORT (MIPS CHIP)
C  5 JUL 89 - FJ  - ADD AMDAHL SUPPORT
C  7 JUN 89 - MWS - ADD ARDENT TITAN SUPPORT
C 10 APR 89 - STE - ABORT IF REQUESTED MEMORY EXCEEDS AMOUNT AVAILABLE
C 22 FEB 89 - STE - PUT ALL THE NASTY MACHINE DEPENDENCIES HERE
C*MODULE UNPORT
C-----------------------------------------------------------------------
C     THIS IS THE NASTIEST, TOTALLY UNPORTABLE CODE IN GAMESS.
C     THE VERSIONS WHICH ARE SUPPORTED HERE ARE
C          * 64 BIT LINUX, USING      GFORTRAN, PGF77, IFORT ...
C            THESE TWO MUST CONFORM TO GNU/GCCLIB CALLS, ONLY.
C          * WIN64 SYSTEMS
C-----------------------------------------------------------------------
C
      MODULE UNPORT
        implicit none
C
C       The version string is also architecture dependent
C
#if     defined(_WIN64)
        character(len=40), parameter :: version_string =
     *    '******** 64 BIT WINDOWS VERSION ********'
#else
        character(len=40), parameter :: version_string =
     *    '********* 64 BIT LINUX VERSION *********'
#endif
#if     defined(_WIN64)
        character(len=1), parameter :: directory_separator = '\'
#else
        character(len=1), parameter :: directory_separator = '/'
#endif
C
C       Determines whether subroutine commit can be called
C
#if     defined(_WIN64) && defined(__INTEL_COMPILER)
        logical, parameter :: commit_supported = .true.
#elif ! defined(_WIN64) && defined(__GFORTRAN__)
        logical, parameter :: commit_supported = .true.
#elif ! defined(_WIN64) && defined(__INTEL_COMPILER)
        logical, parameter :: commit_supported = .true.
#elif ! defined(_WIN64) && defined(__NVCOMPILER)
        logical, parameter :: commit_supported = .true.
#elif ! defined(_WIN64) && defined(__AOCC__)
        logical, parameter :: commit_supported = .true.
#elif ! defined(_WIN64) && defined(__ibmxl__)
        logical, parameter :: commit_supported = .true.
#else
        logical, parameter :: commit_supported = .false.
#endif
C
C       WINDOWS Sleep function expects milliseconds, not seconds
C
#if defined(_WIN64)
        integer, parameter :: seconds_to_delay = 1000
#else
        integer, parameter :: seconds_to_delay = 1
#endif
C
C       WINDOWS does not support getpid and raise.
C
#if ! defined(_WIN64)
        logical, parameter :: debug_wait_supported = .true.
#else
        logical, parameter :: debug_wait_supported = .false.
#endif
        !>
        !> @brief interface to POSIX and Windows sleep routines
        !>
        interface
#if defined(_WIN64)
          function sleep(duration) bind(C, name="Sleep")
#else
          function sleep(duration) bind(C, name="sleep")
#endif
            use iso_c_binding, only: c_int
            import
            integer(c_int) :: sleep
            integer(c_int), intent(in), value :: duration
          end function sleep
#if   ! defined(_WIN64)
C>
C>        @brief   Interface to POSIX fsync.
C>
C>        @details Transfers all modified in- core data
C>                 of the file referred to by fd to disk.
C>                 The call  blocks until the device
C>                 reports that the transfer has completed.
C>
C>        @author Christian Friedl
C>
C>        @date   Jul, 2022 Initial release
C>
          function fsync(fd) bind(c,name="fsync")
          use iso_c_binding, only: c_int
            integer(c_int), value :: fd
            integer(c_int) :: fsync
          end function fsync
C>
C>        @brief  Interface to getfd function.
C>
C>        @detail Returns the underlying file
C>                descriptor given a Fortran
C>                logical unit. Compiler dependent.
C>
C>        @author Christian Friedl
C>
C>        @date   Jul, 2022 Initial release
C>
#if   defined(__NVCOMPILER)
          function getfd(lu)
            integer(kind=4) :: lu
            integer(kind=4) :: getfd
          end function getfd
#elif defined(__AOCC__)
C         AOCC is hard to identify this is not a predefined macro
          function getfd(lu)
            integer(kind=4) :: lu
            integer(kind=4) :: getfd
          end function getfd
#elif defined(__ibmxl__)
          function getfd_(lu)
            integer(kind=4) :: lu
            integer(kind=4) :: getfd_
          end function getfd_
#endif
C>
C>        @brief   Interface to POSIX getpid.
C>
C>        @author Christian Friedl
C>
C>        @date   Sep, 2022 Initial release
C>
          function getpid() bind(c,name="getpid")
          use iso_c_binding, only: c_int
            integer(c_int) :: getpid
          end function getpid
C>
C>        @brief   Interface to POSIX raise.
C>
C>        @author Christian Friedl
C>
C>        @date   Sep, 2022 Initial release
C>
          function raise(sig) bind(c,name="raise")
          use iso_c_binding, only: c_int
            integer(c_int), value :: sig
            integer(c_int) :: raise
          end function raise
#endif
        end interface
      contains
C>
C>      @brief  Commit dirty data of logical unit
C>              to stable storage.
C>
C>      @detail Blocks until the data is commited.
C>              Does nothing if compiler is
C>              unsupported or if the logical
C>              unit is not connected to a file.
C>
C>      @author Christian Friedl
C>
C>      @date   Jul, 2022 Initial release
C>
        subroutine commit(lu)
#if   defined(_WIN64)  &&  defined(__INTEL_COMPILER)
        use ifcore
        implicit none
        integer, intent(in) :: lu
        integer(kind=4) :: ret4
        logical :: retl
        integer(kind=4) :: lu4
        lu4 = int(lu, kind=4)
        retl = commitqq(lu4)
        return
#elif ! defined(_WIN64) && defined(__GFORTRAN__)
        implicit none
        integer, intent(in) :: lu
        integer(kind=4) :: ret4
        integer(kind=4) :: fd4, lu4
        lu4 = int(lu, kind=4)
        fd4 = fnum(lu4)
        ret4 = fsync(fd4)
        return
#elif ! defined(_WIN64) && defined(__INTEL_COMPILER)
        use ifposix
        implicit none
        integer, intent(in) :: lu
        integer(kind=4) :: ret4
        integer(kind=4) :: fd4, ierror4, lu4
        lu4 = int(lu, kind=4)
        call pxffileno(lu4, fd4, ierror4)
        if (ierror4 .ne. 0) return
        ret4 = fsync(fd4)
        return
#elif ! defined(_WIN64) && defined(__NVCOMPILER)
        implicit none
        integer, intent(in) :: lu
        integer(kind=4) :: fd4, lu4
        integer(kind=4) :: ret4
        lu4 = int(lu, kind=4)
        fd4 = getfd(lu4)
        if (fd4 .eq. -1) return
        ret4 = fsync(fd4)
        return
#elif ! defined(_WIN64) && defined(__AOCC__)
C       AOCC is hard to identify this is not a predefined macro
        implicit none
        integer, intent(in) :: lu
        integer(kind=4) :: ret4
        integer(kind=4) :: fd4, lu4
        lu4 = int(lu, kind=4)
        fd4 = getfd(lu4)
        if (fd4 .eq. -1) return
        ret4 = fsync(fd4)
        return
#elif ! defined(_WIN64) && defined(__ibmxl__)
        implicit none
        integer, intent(in) :: lu
        integer(kind=4) :: ret4
        integer(kind=4) :: fd4, lu4
        lu4 = int(lu, kind=4)
        fd4 = getfd_(lu4)
        if (fd4 .eq. -1) return
        ret4 = fsync(fd4)
        return
#else
C       Do nothing if compiler is unsupported.
        implicit none
        integer, intent(in) :: lu
        return
#endif
        end subroutine
C>
C>      @brief  Wait for debugger to attach.
C>
C>      @author Christian Friedl
C>
C>      @date   Sep, 2022 Initial release
C>
        subroutine debug_wait
        implicit none
#if ! defined(_WIN64)
        character(len=8) :: val
        integer itmp
        call get_environment_variable("GMS_DEBUG_WAIT",val,itmp)
        if(itmp.GT.0) THEN
            WRITE(6,*) "My pid is ",getpid()," and I will stop now."
            itmp = raise(19_4)
            WRITE(6,*) "I have continued."
        endif
#endif
        end subroutine
      END MODULE UNPORT
