#!/bin/bash -evx
#COBALT -n 8
#COBALT -t 120
#COBALT -O output.log
#COBALT -q default
#COBALT -A AdvElecStructPr_tesp

cp 2nm.inp JOB.$COBALT_JOBID.F05

rpn=4
allranks=$((COBALT_JOBSIZE*rpn))
threads=64

aprun -n $allranks \
      -N $rpn \
      -d $threads \
      -cc depth \
      -j 4 \
      --env OMP_NUM_THREADS=$threads \
      --env I_MPI_PIN_DOMAIN=64:compact \
      --env KMP_AFFINITY=scatter \
      --env KMP_STACKSIZE=2000m \
      --env OUTPUT=JOB.$COBALT_JOBID.F06 --env TRAJECT=JOB.$COBALT_JOBID.F04 --env ERICFMT="/gpfs/mira-home/yuri/dist/Github/gamess-theta/auxdata/ericfmt.dat" --env IRCDATA=JOB.$COBALT_JOBID.irc --env INPUT=JOB.$COBALT_JOBID.F05 --env PUNCH=JOB.$COBALT_JOBID.dat --env EXTBAS=JOB.$COBALT_JOBID.bas --env AOINTS=JOB.$COBALT_JOBID.F08 --env MOINTS=JOB.$COBALT_JOBID.F09 --env DICTNRY=JOB.$COBALT_JOBID.F10 --env DRTFILE=JOB.$COBALT_JOBID.F11 --env CIVECTR=JOB.$COBALT_JOBID.F12 --env CASINTS=JOB.$COBALT_JOBID.F13 --env CIINTS=JOB.$COBALT_JOBID.F14 --env WORK15=JOB.$COBALT_JOBID.F15 --env WORK16=JOB.$COBALT_JOBID.F16 --env CSFSAVE=JOB.$COBALT_JOBID.F17 --env FOCKDER=JOB.$COBALT_JOBID.F18 --env WORK19=JOB.$COBALT_JOBID.F19 --env DASORT=JOB.$COBALT_JOBID.F20 --env DFTINTS=JOB.$COBALT_JOBID.F21 --env DFTGRID=JOB.$COBALT_JOBID.F22 --env JKFILE=JOB.$COBALT_JOBID.F23 --env ORDINT=JOB.$COBALT_JOBID.F24 --env EFPIND=JOB.$COBALT_JOBID.F25 --env PCMDATA=JOB.$COBALT_JOBID.F26 --env PCMINTS=JOB.$COBALT_JOBID.F27 --env SVPWRK1=JOB.$COBALT_JOBID.F26 --env SVPWRK2=JOB.$COBALT_JOBID.F27 --env MLTPL=JOB.$COBALT_JOBID.F28 --env MLTPLT=JOB.$COBALT_JOBID.F29 --env DAFL30=JOB.$COBALT_JOBID.F30 --env SOINTX=JOB.$COBALT_JOBID.F31 --env SOINTY=JOB.$COBALT_JOBID.F32 --env SOINTZ=JOB.$COBALT_JOBID.F33 --env SORESC=JOB.$COBALT_JOBID.F34 --env SIMEN=JOB.$COBALT_JOBID.simen --env SIMCOR=JOB.$COBALT_JOBID.simcor --env GCILIST=JOB.$COBALT_JOBID.F37 --env HESSIAN=JOB.$COBALT_JOBID.F38 --env SOCCDAT=JOB.$COBALT_JOBID.F40 --env AABB41=JOB.$COBALT_JOBID.F41 --env BBAA42=JOB.$COBALT_JOBID.F42 --env BBBB43=JOB.$COBALT_JOBID.F43 --env MCQD50=JOB.$COBALT_JOBID.F50 --env MCQD51=JOB.$COBALT_JOBID.F51 --env MCQD52=JOB.$COBALT_JOBID.F52 --env MCQD53=JOB.$COBALT_JOBID.F53 --env MCQD54=JOB.$COBALT_JOBID.F54 --env MCQD55=JOB.$COBALT_JOBID.F55 --env MCQD56=JOB.$COBALT_JOBID.F56 --env MCQD57=JOB.$COBALT_JOBID.F57 --env MCQD58=JOB.$COBALT_JOBID.F58 --env MCQD59=JOB.$COBALT_JOBID.F59 --env MCQD60=JOB.$COBALT_JOBID.F60 --env MCQD61=JOB.$COBALT_JOBID.F61 --env MCQD62=JOB.$COBALT_JOBID.F62 --env MCQD63=JOB.$COBALT_JOBID.F63 --env MCQD64=JOB.$COBALT_JOBID.F64 --env NMRINT1=JOB.$COBALT_JOBID.F61 --env NMRINT2=JOB.$COBALT_JOBID.F62 --env NMRINT3=JOB.$COBALT_JOBID.F63 --env NMRINT4=JOB.$COBALT_JOBID.F64 --env NMRINT5=JOB.$COBALT_JOBID.F65 --env NMRINT6=JOB.$COBALT_JOBID.F66 --env DCPHFH2=JOB.$COBALT_JOBID.F67 --env DCPHF21=JOB.$COBALT_JOBID.F68 /gpfs/mira-home/yuri/dist/Github/gamess-theta/gamess.00.x

exit $?
