#!/bin/bash
#
#   make a compressed tar file (of the ASCII information only)
#
#   Note that this script should be run from ${GMS_PATH} directory
#   Please, firstly clone GAMESS repo, and then run in as `./misc/wrapgms`
#
echo "# Commit ID" > VERSION.md
git rev-parse --verify HEAD >> VERSION.md
echo "# Version" >> VERSION.md
echo $1 >> VERSION.md
CURDIR=.
#
#   Download 3rd-party libraries and its tests for GAMESS
#
./tools/mdi/download-mdi.csh
./tools/libxc/download-libxc.csh
./tools/libxc/download-libxc-tests.csh
./tools/lapack/download-lapack.csh
#
#   Create single-file archive
#
tar -cvf ${CURDIR}/gamess.tar --transform 's,^..,gamess/,' \
                              --exclude .git   \
                              --exclude .gitattributes \
                              --exclude .github \
                              --exclude .gitignore \
                              --exclude manual \
                              --exclude tinker \
                              --exclude clg   \
                              --exclude '*.x' \
                              --exclude '*.a' \
                              --exclude '*.o' \
                              --exclude '*.zip' \
                              --exclude '*.tar.gz' \
                              --exclude '*/coverage.dat.*' \
                              --exclude Makefile \
                              --exclude .travis.yml \
                              --exclude .travis.yml.with.libcchem \
                              --exclude install.info \
                              --exclude tests/TIMINGS.md \
                              --exclude tests/TIMINGS.xlsx \
                              --exclude graphics \
                              --exclude tools/gerrit \
                              ${CURDIR}
ls -lF ${CURDIR}/gamess.tar
#
#   Compress archive
#
gzip   ${CURDIR}/gamess.tar
ls -lF ${CURDIR}/gamess.tar.gz
#
#   Copy compressed to ${HOME}
#
cp ${CURDIR}/gamess.tar.gz ${HOME}/gamess.tar.gz
