#!/bin/bash



finalE0=-23.4574017024

finalE=`grep "FINAL R-PM6 ENERGY IS" $1 | head -n 1 | awk '{print $5}'`

tolE0=$tolE

error=0

#total energy
diffe=`$chkabs $finalE0 $finalE $tolE0`
if [ $? -ne 0 ]
then
  error=$((error + 1))
fi

printf "RPM6error=%12.8f\n" $diffe
exit $error
